version: '3.6'

services:

  nginx:
    build: ./docker/nginx

    hostname: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - test-network

  web:
    image: josefjebavy/debian-apache-php7.4-nette

    hostname: web
    environment:       
     - NETTE_DEBUG=1
     - TZ=Europe/Prague
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 8080:80
      - 4443:443

    networks:
      - test-network



networks:
  test-network:
    driver: bridge
